apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-daemonset
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
  labels:
    app: busybox
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: sleep
          image: busybox
          command: ["/bin/sh", "-ec", "sleep 1000"]
          volumeMounts:
            - name: mnt-vol
              mountPath: /data
      volumes:
        - name: mnt-vol
          persistentVolumeClaim:
            claimName: test-pvc-daemonset
